// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gozasfvvgshljziijuwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvemFzZnZ2Z3NobGp6aWlqdXdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4OTcwNjQsImV4cCI6MjA3MDQ3MzA2NH0.6BDaIs3vxmiUCHlokGMMzbOmOLWYJIboAgWHO0bHcQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});