name: Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
        env:
          CI: false
      
      - name: Build app
        run: npm run build
      
      - name: List dist contents  # Debugging: Check if build produced files
        run: ls -R ./dist/ || echo "No dist folder found - build may have failed"
      
      - name: Deploy to server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: public_html/  # Try without leading '/' first; adjust based on FTP client test
          protocol: ftp
          dry-run: true  # Temporary: Logs actions without applying; remove after debugging
          dangerous-clean-slate: true  # Temporary: Forces full upload; remove after first success
          log-credentials-on-error: true  # For debug if connection issues
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
