name: Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
        env:
          CI: false
      
      - name: Build app
        run: npm run build
      
      - name: List dist contents  # Optional: Keep for now to confirm files
        run: ls -R ./dist/ || echo "No dist folder found - build may have failed"
      
      - name: Deploy to server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/  # Trailing / ensures contents only (no nested dist folder)
          server-dir: public_html/  # Adjust if needed (e.g., ./ or /home/yourusername/public_html/)
          protocol: ftp  # Change to 'ftps' if supported
          dry-run: false  # Now actually deploys!
          dangerous-clean-slate: true  # For first real run; set to false after
          log-credentials-on-error: true
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
